common:
    lid_topic:  "/velodyne_points"
    imu_topic:  "/imu/data_raw"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                  # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

preprocess:
    lidar_type: 2                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 32
    scan_rate: 10                # only need to be set for velodyne, unit: Hz,
    timestamp_unit: 0            # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    blind: 0
    blind_bbox_en: true   # true 为开启过滤，false 为关闭
    blind_bbox: [-3.0, 0.0, -0.5, 0.5, -0.8, 1.0]    # 新增: 剔除自身车体 [x_min, x_max, y_min, y_max, z_min, z_max] (单位: 米)坐标系是雷达坐标系，通常 前为x正, 左为y正, 上为z正，请根据实际车体尺寸测量后填入,

mapping:
    acc_cov: 0.2
    gyr_cov: 0.2
    b_acc_cov: 0.0002
    b_gyr_cov: 0.0002
    fov_degree:    360
    det_range:     100.0
    extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic,
    extrinsic_T: [ -0.054077, 0.090664, 0.131179 ]
    extrinsic_R: [ 0.999818,  0.019088, -0.000266,
              -0.019080,  0.999660,  0.017745,
               0.000604, -0.017736,  0.999843 ]
    extrinsic_T_rtk: [-0.30, 0.45, 0.13] # 必填！你的 RTK 天线中心，相对于 IMU 中心的 [X, Y, Z] 物理距离，单位米。比如天线在IMU正上方40cm，就是[0,0,0.4]。

publish:
    path_en:  true
    scan_publish_en:  false       # false: close all the point cloud output
    dense_publish_en: false       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: false                    # true: 开启点云保存功能; false: 关闭
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
    pcd_save_radius_en: false     # true: only save the points within a certain radius from the trajectory center; false: save all points
    pcd_save_radius: 3.5         # the radius for saving points, unit: meter, only works when pcd_save_radius_en is true. This can help save disk space

path_save:
    path_save_en: true                     # true: 开启轨迹保存功能; false: 关闭
    path_save_name: "FAST-LIO-RTK-build.txt"    # 在这里可以随意修改你要保存的 txt 名称
