common:
    lid_topic:  "/point_cloud_raw"
    imu_topic:  "/imu/data_raw"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                  # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

preprocess:
    lidar_type: 5                # Leishen C16/C32 PointXYZIRT
    scan_line: 32
    scan_rate: 10                # only need to be set for velodyne, unit: Hz,
    timestamp_unit: 0            # LSLIDAR handler converts absolute seconds to relative milliseconds.
    blind: 1

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    360
    det_range:     100.0
    extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic,
    extrinsic_T: [ -0.054077, 0.090664, 0.131179]
    extrinsic_R: [ 0.999818,  0.019088, -0.000266,
              -0.019080,  0.999660,  0.017745,
               0.000604, -0.017736,  0.999843]

publish:
    path_en:  true
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en:   false     # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: false
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
trajectory_save:
    tum_save_en: true
    tum_file_path: "/home/gsm/新结果/FAST_LIO2.txt"
    save_lidar_pose: false
